# Generated by Django 5.0.3 on 2024-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
