# Generated by Django 5.0.3 on 2024-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_author_dod'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
