# Generated by Django 5.0.3 on 2024-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
