# Generated by Django 5.0.3 on 2024-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_available_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=25.0),
            preserve_default=False,
        ),
    ]
